### ISSUE TITLE
Hi, I got an Error when I import keras_ocr, could you help me solve the problem?

### ISSUE THREAD

**Issue by JimXu1989** [faustomorales/keras-ocr#42]
I have tensorflow 2.0.0 python 3.7
When I import keras_ocr
I got the error:
2020-03-11 08:32:13.540050: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jim\Anaconda3\Lib\site-packages\keras_ocr\__init__.py", line 1, in <module>
    from . import (detection, recognition, tools, data_generation, pipeline, evaluation, datasets,
  File "C:\Users\jim\Anaconda3\Lib\site-packages\keras_ocr\detection.py", line 31, in <module>
    from . import tools
  File "C:\Users\jim\Anaconda3\Lib\site-packages\keras_ocr\tools.py", line 14, in <module>
    from shapely import geometry
  File "C:\Users\jim\Anaconda3\Lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\jim\Anaconda3\Lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\jim\Anaconda3\Lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\jim\Anaconda3\Lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\jim\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by faustomorales** [comment]
This appears to be the same issue as https://github.com/faustomorales/keras-ocr/issues/31 (a problem with installing `shapely`). Please take a look there to see if the solution at the end of the thread helps resolve your issue.

**Comment by faustomorales** [comment]
Closing this issue because it appears to have been previously resolved for other users and no response has been provided for some time.
