### ISSUE TITLE
AttributeError: module 'keras_ocr' has no attribute 'pipeline'

### ISSUE THREAD

**Issue by abhilashchowdhary** [faustomorales/keras-ocr#78]
I installed the package via `pip` in a fresh virutalenv with python 3.7.3 on Ubuntu. However, when I tried running the model, I get this import error

```
$ python keras_ocr.py 
Traceback (most recent call last):
  File "keras_ocr.py", line 3, in <module>
    import keras_ocr
  File "/home/playground/keras-ocr/keras_ocr.py", line 7, in <module>
    pipeline = keras_ocr.pipeline.Pipeline()
AttributeError: module 'keras_ocr' has no attribute 'pipeline'
```

Following is the output of `pip freeze` in my virtualenv

```
$ pip freeze
absl-py==0.9.0
astor==0.8.1
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
editdistance==0.5.3
efficientnet==1.0.0
essential-generators==0.9.2
fonttools==4.10.0
gast==0.2.2
google-auth==1.14.3
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
imagecodecs==2020.2.18
imageio==2.8.0
imgaug==0.4.0
importlib-metadata==1.6.0
Keras-Applications==1.0.8
keras-ocr==0.8.3
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.2.1
networkx==2.4
numpy==1.18.4
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
Pillow==7.1.2
protobuf==3.12.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyclipper==1.1.0.post3
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
scikit-image==0.17.2
scipy==1.4.1
Shapely==1.7.0
six==1.14.0
tensorboard==2.1.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
tifffile==2020.5.11
tqdm==4.46.0
urllib3==1.25.9
validators==0.15.0
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
```

Not sure what would be the source of this error. Any help would be much appreciated.

**Comment by abhilashchowdhary** [comment]
This was because I had cloned the repo in the same location and python was looking for module `pipelines` in the root of the repo.
