### ISSUE TITLE
The cudnn version does not match the source code

### ISSUE THREAD

**Issue by jackCplusplus** [faustomorales/keras-ocr#85]
System:
   ```
    win10
    anaconda 4.8.3
    CUDA10.1 Cudnn7.6.5
    CUDA 10.0 Cudnn7.6.5
    CUDA9.2 Cudnn7.1.4
```
hardware
	
```

OS	                Windows 10 x64 ( DirectX 12 )
CPU	                AMD Ryzen 5 2600X six core
RAM	                8 GB ( 十铨 DDR4 2400MHz )
Graphics card :	        Nvidia GeForce GTX 1070 Ti ( 8 GB / 索泰 )

```

pip list
```
Package                  Version
------------------------ -------------------
absl-py                  0.9.0
astor                    0.8.1
astunparse               1.6.3
cachetools               4.1.0
certifi                  2020.4.5.1
chardet                  `3.0.4`
cycler                   0.10.0
decorator                4.4.2
editdistance             0.5.3
efficientnet             1.0.0
essential-generators     0.9.2
fonttools                4.10.2
gast                     0.3.3
google-auth              1.15.0
google-auth-oauthlib     0.4.1
google-pasta             0.2.0
grpcio                   1.29.0
h5py                     2.10.0
idna                     2.9
imagecodecs              2020.2.18
imageio                  2.8.0
imgaug                   0.4.0
importlib-metadata       1.6.0
Keras-Applications       1.0.8
keras-ocr                0.8.3.post0.dev2
Keras-Preprocessing      1.1.2
kiwisolver               1.2.0
Markdown                 3.2.2
matplotlib               3.2.1
networkx                 2.4
numpy                    1.18.4
oauthlib                 3.1.0
opencv-python            4.2.0.34
opt-einsum               3.2.1
Pillow                   7.1.2
pip                      20.0.2
protobuf                 3.12.1
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyclipper                1.1.0.post3
pyparsing                2.4.7
PyQt5                    5.12
PyQt5-sip                4.19.19
PyQtWebEngine            5.12
python-dateutil          2.8.1
PyWavelets               1.1.1
requests                 2.23.0
requests-oauthlib        1.3.0
rsa                      4.0
scikit-image             0.17.2
scipy                    1.4.1
setuptools               46.4.0.post20200518
Shapely                  1.6.4.post2
six                      1.15.0
tensorboard              2.2.1
tensorboard-plugin-wit   1.6.0.post3
tensorflow               2.2.0
tensorflow-estimator     2.2.0
tensorflow-gpu           2.2.0
tensorflow-gpu-estimator 2.2.0
termcolor                1.1.0
tifffile                 2020.5.11
tqdm                     4.46.0
typed-ast                1.4.0
urllib3                  1.25.9
validators               0.15.0
Werkzeug                 1.0.1
wheel                    0.34.2
wincertstore             0.2
wrapt                    1.12.1
zipp                     3.1.0
```
demo 
```
import matplotlib.pyplot as plt

import keras_ocr
import cv2
import tensorflow as tf

# Get a set of three example images
images = [
    keras_ocr.tools.read(url) for url in [
        '.\debug\Army_Reserves_Recruitment_Banner_MOD_45156284.jpg',
        '.\debug\EUBanana-500x112.jpg',
        '.\debug\FseeG2QeLXo.jpg'
    ]
]

for image in images:
    cv2.imshow("sds",image)
    cv2.waitKey(1000)

# keras-ocr will automatically download pretrained
# weights for the detector and recognizer.
pipeline = keras_ocr.pipeline.Pipeline()
# Each list of predictions in prediction_groups is a list of
# (word, box) tuples.
prediction_groups = pipeline.recognize(images)

# Plot the predictions
fig, axs = plt.subplots(nrows=len(images), figsize=(20, 20))
for ax, image, predictions in zip(axs, images, prediction_groups):
    keras_ocr.tools.drawAnnotations(image=image, predictions=predictions, ax=ax)
```
LOG:
```
2020-05-26 19:26:12.933307: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Looking for C:\Users\有对象真好\.keras-ocr\craft_mlt_25k.h5
2020-05-26 19:26:18.511098: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-05-26 19:26:18.532685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: GeForce GTX 1070 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 19 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.66GiB/s
2020-05-26 19:26:18.532990: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-05-26 19:26:18.542287: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-05-26 19:26:18.551168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-05-26 19:26:18.552702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-05-26 19:26:18.563451: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-05-26 19:26:18.570929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-05-26 19:26:18.594078: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-05-26 19:26:18.594736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-26 19:26:18.595266: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-05-26 19:26:18.603662: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1fccfb8f630 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-26 19:26:18.603925: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-26 19:26:18.604430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: GeForce GTX 1070 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 19 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.66GiB/s
2020-05-26 19:26:18.604757: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-05-26 19:26:18.604923: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-05-26 19:26:18.605146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-05-26 19:26:18.605295: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-05-26 19:26:18.605446: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-05-26 19:26:18.605593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-05-26 19:26:18.605739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-05-26 19:26:18.606221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-26 19:26:19.142272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-26 19:26:19.142469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-05-26 19:26:19.142564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-05-26 19:26:19.143194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6285 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
2020-05-26 19:26:19.145649: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1fcee37aa00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-26 19:26:19.145844: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1070 Ti, Compute Capability 6.1
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\keras\backend.py:5871: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Looking for C:\Users\有对象真好\.keras-ocr\crnn_kurapan.h5
2020-05-26 19:26:22.789888: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-05-26 19:26:23.528811: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.5.0 but source was compiled with: 7.6.5.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-05-26 19:26:23.531500: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.5.0 but source was compiled with: 7.6.5.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "C:/PycharmProjects/keras_cor_build/main.py", line 25, in <module>
    prediction_groups = pipeline.recognize(images)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\keras_ocr\pipeline.py", line 55, in recognize
    box_groups = self.detector.detect(images=images, **detection_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\keras_ocr\detection.py", line 678, in detect
    boxes = getBoxes(self.model.predict(np.array(images), **kwargs),
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1268, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\eager\def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\eager\function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model_1/basenet.slice1.0/Conv2D (defined at \ProgramData\Anaconda3\envs\tensorflow2.1\lib\site-packages\keras_ocr\detection.py:678) ]] [Op:__inference_predict_function_6881]

Function call stack:
predict_function


```
Loaded runtime CuDNN library: 7.5.0 but source was compiled with: 7.6.5. What's true problem?is my Graphics card's memory too small? or something else? have u ever happened this ?

**Comment by faustomorales** [comment]
This is not a `keras-ocr` error but rather a version mismatch problem between TensorFlow, CUDA, and CuDNN. CUDA 10.x requires CuDNN >= 7.6.4 (please see the [NVIDIA support matrix](https://docs.nvidia.com/deeplearning/sdk/cudnn-support-matrix/index.html)). In this case, the TensorFlow build you're using specifically requires CuDNN 7.6.5 (as indicated in the error message). Please install CuDNN 7.6.5.

**Comment by jackCplusplus** [comment]
CuDNN 7.6.5 has been determined to be installed, perhaps the problem is not as the surface suggests

**Comment by jackCplusplus** [comment]
path `C:\Windows\System` have a lower version cudnn.dll ,So that explains what happened up there.
